# config.yaml
project:
  name: bundestage_speeches
  seed: 42

paths:
  data_dir: ./data
  model_dir: ./models
  logs_dir: ./logs

data:
  xml_file: https://www.bundestag.de/resource/blob/1115000/21032.xml
  train_file: train.csv
  test_file: test.csv
  text_column: text
  label_column: label
  shuffle: true

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.0003
  optimizer: adam
  device: cuda    # oder "cpu"

summarization:
  model: t5-small
  tokenizer: t5-small
  max_length: 1100
  min_length: 700
  metric : ("rouge1", "rouge2", "rougeL")

sentiment_analysis:
  model: bert
  tokenizer: bert-base-german-cased
  num_labels: 3


fact_checking:
  model: bert
  tokenizer: bert-base-german-cased


logging:
  level: INFO
  save_every: 1
